Added extension permissions in core
Dative-GPI/foundation-extension pull request #52
Opened 2024-12-20 10:21 UTC by rduteil

2024-12-20 14:42 UTC, gballigand approved these changes

2024-12-20 14:42 UTC, gballigand commented on src/app/Foundation.Extension.Core-UI/components/FEEditPermissionsGrid.vue
j'aurai juste mis un props edit avec un seul composant pour edit et liste

2024-12-20 14:42 UTC, gballigand commented on src/app/Foundation.Extension.Core/DI/Injectors/RolePermissionOrganisationInjector.cs
Possibilité de faire une queryParent avec seulement 1 handler au lieu de 3

2024-12-21 12:21 UTC, SchroterQuentin requested changes
Je ne comprends pas pourquoi on parle de ServiceAccount dans les extensions alors que ça n'existait pas jusqu'à maintenant et que les extensions les traitaient comme des rôles "classics"

2025-01-06 15:26 UTC, rduteil commented on src/app/Foundation.Extension.Core-UI/components/FEEditPermissionsGrid.vue
ça copie le fonctionnement de DAT Foundation et j'aime bien l'idée

2025-01-06 16:34 UTC, rduteil commented
Plus qu'un seul endpoint, retour des RoleOrganisationId, RoleOrganisationTypeId dans la colonne RoleId (renommée depuis RoleOrganisationId mais pas besoin de migration). Perte de la possibilité de vérifier les permissions

2025-01-07 11:28 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core-UI/components/FEPermissionsGrid.vue
> +    admin: {
Je comprends pas pourquoi on a besoin de ce admin, c'est juste un composant qui doit afficher les permissions pour moi

2025-01-07 13:22 UTC, rduteil commented on src/app/Foundation.Extension.Core-UI/components/FEPermissionsGrid.vue
> +    admin: {
Y'a besoin de l'information admin au moins sur le parent de ce composant pour savoir si on doit utiliser les permissions d'un role ou du type d'organisation, et juste au lieu de fetch les permissions totales dans le parent j'ai pris le parti de dire à la FEPermissionsGrid qui elle va toujours fetcher les permissions totales, de mettre ce props pour lui dire "Tout ce que tu fetch, c'est une permission dispo vu qu'on affiche les permissions de l'admin"

2025-01-07 13:22 UTC, rduteil commented on src/app/Foundation.Extension.Core-UI/components/FEPermissionsGrid.vue
> +    admin: {
Sinon dans le parent je fetch les deux sets et je les passes, mais là ça fait un fetch de moins en échange du passage d'un props ça me paraissait pas déconnant

2025-01-13 12:55 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core-UI/components/FEEditPermissionsGrid.vue
> +            .filter(item => JSON.stringify(item).toLowerCase().includes(search.value.toLowerCase()));
containsSearchTerm

2025-01-13 12:56 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core-UI/components/FEPermissionsGrid.vue
> +            .filter(item => JSON.stringify(item).toLowerCase().includes(search.value.toLowerCase()));
Même chose ici

2025-01-28 21:44 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core/Handlers/QueryHandlers/UserOrganisations/CurrentUserOrganisationQueryHandler.cs
> +			var permissions = new List<PermissionItem>();
On peut juste définir la variable sans l'initialiser et mettre dans le switch un default qui throw une exception

2025-01-28 21:44 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core/Handlers/QueryHandlers/UserOrganisations/CurrentUserOrganisationQueryHandler.cs
> +                        .Where(p => permissionOrganisationTypes.Select(pot => pot.PermissionCode).Contains(p.Code))
Bof les perfs de cette algo, je pense le mieux ici c'est de faure un join qui va auto supprimer les permissions qui sont pas dans les deux sets. On en discute si tu vois pas ce que je veux dire.

2025-01-28 21:44 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core/Handlers/QueryHandlers/UserOrganisations/UserOrganisationQueryHandler.cs
> +                    permissions = roleOrganisation.Permissions
Idem ici

2025-01-28 21:44 UTC, SchroterQuentin commented on src/app/Foundation.Extension.Core/Services/Providers/PermissionProvider.cs
> +            switch (userOrganisation.RoleType) {
On est sure qu'on a pas déjà les permissions dans le userOrganisation ?

2025-01-29 09:22 UTC, rduteil commented on src/app/Foundation.Extension.Core/Handlers/QueryHandlers/UserOrganisations/CurrentUserOrganisationQueryHandler.cs
> +			var permissions = new List<PermissionItem>();
Fait mais avec une liste vide plutôt qu'un throw (Dans les 3 fichiers où il y avait quelque chose de semblable : CurrentUserOrganisationQueryHandler, UserOrganisationQueryHandler, PermissionProvider)

2025-01-29 09:23 UTC, rduteil commented on src/app/Foundation.Extension.Core/Handlers/QueryHandlers/UserOrganisations/CurrentUserOrganisationQueryHandler.cs
> +                        .Where(p => permissionOrganisationTypes.Select(pot => pot.PermissionCode).Contains(p.Code))
roleOrganisation.Permissions.IntersectBy(permissionOrganisationTypes.Select(pot => pot.PermissionCode), p => p.Code) pour faire plus succint

2025-01-29 09:24 UTC, rduteil commented on src/app/Foundation.Extension.Core/Services/Providers/PermissionProvider.cs
> +            switch (userOrganisation.RoleType) {
On a les permissions de DAT'Foundation mais il faut ajouter les permissions de l'extension

2025-01-29 09:54 UTC, SchroterQuentin approved these changes

2025-01-29 09:54 UTC, merged